name: Python CI

# 触发条件：代码推送到 main 分支或有 pull request 时
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# 定义作业
jobs:
  test:
    name: Run Tests
    # 指定运行环境（Ubuntu 最新版）
    runs-on: ubuntu-latest

    # 定义 Python 版本矩阵
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    # 步骤
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Python 环境
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 运行测试
      - name: Run tests
        run: |
          pytest tests/ --verbose